version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: few_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: few_user
      POSTGRES_PASSWORD: few_password
      POSTGRES_DB: few_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U few_user -d few_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: